import { Subject } from '@/types'

const ALL_SUBJECTS: (Subject & { grades: number[] })[] = [
  {
    id: 'math',
    name: 'Mathematics',
    nameMk: 'Математика',
    world: 'Кристални пештери',
    color: '#5C35D4',
    bgColor: '#EDE9FF',
    emoji: '🔮',
    unitsCount: 4,
    grades: [1, 2, 3, 4, 5, 6, 7, 8, 9],
  },
  {
    id: 'mk',
    name: 'Macedonian Language',
    nameMk: 'Македонски јазик',
    world: 'Зборовен свет',
    color: '#E84393',
    bgColor: '#FFE8F5',
    emoji: '📖',
    flagCode: 'mk',
    unitsCount: 7,
    grades: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 'science',
    name: 'Natural Sciences',
    nameMk: 'Природни науки',
    world: 'Планетата Земја',
    color: '#6BCB77',
    bgColor: '#E8F8EA',
    emoji: '🌍',
    unitsCount: 5,
    grades: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 'society',
    name: 'Society',
    nameMk: 'Општество',
    world: 'Светот околу мене',
    color: '#7C3AED',
    bgColor: '#EDE9FE',
    emoji: '🏘️',
    unitsCount: 4,
    grades: [1, 2, 3, 4],
  },
  {
    id: 'enviro',
    name: 'Nature & Society',
    nameMk: 'Запознавање на околината',
    world: 'Природен свет',
    color: '#16A34A',
    bgColor: '#DCFCE7',
    emoji: '🌱',
    unitsCount: 3,
    grades: [1, 2, 3, 4],
  },
  {
    id: 'english',
    name: 'English',
    nameMk: 'Англиски јазик',
    world: 'English World',
    color: '#DC2626',
    bgColor: '#FEE2E2',
    emoji: '🌐',
    flagCode: 'gb',
    unitsCount: 4,
    grades: [1, 2, 3, 4, 5, 6],
  },
  {
    id: 'tech',
    name: 'Technical Education & Informatics',
    nameMk: 'Техничко образование и информатика',
    world: 'Дигитален свет',
    color: '#0EA5E9',
    bgColor: '#E0F2FE',
    emoji: '💻',
    unitsCount: 3,
    grades: [5, 6],
  },
  {
    id: 'history',
    name: 'History & Society',
    nameMk: 'Историја и општество',
    world: 'Временска машина',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    emoji: '🏛️',
    unitsCount: 3,
    grades: [5, 6],
  },
  {
    id: 'italian',
    name: 'Italian',
    nameMk: 'Италијански јазик',
    world: 'Il Mondo Italiano',
    color: '#16A34A',
    bgColor: '#DCFCE7',
    emoji: '🇮🇹',
    flagCode: 'it',
    unitsCount: 3,
    grades: [6],
  },
  {
    id: 'french',
    name: 'French',
    nameMk: 'Француски јазик',
    world: 'Le Monde Français',
    color: '#2563EB',
    bgColor: '#EFF6FF',
    emoji: '🇫🇷',
    flagCode: 'fr',
    unitsCount: 3,
    grades: [6],
  },
  {
    id: 'german',
    name: 'German',
    nameMk: 'Германски јазик',
    world: 'Deutsch Welt',
    color: '#F59E0B',
    bgColor: '#FEF3C7',
    emoji: '🇩🇪',
    flagCode: 'de',
    unitsCount: 3,
    grades: [6],
  },
  {
    id: 'biology',
    name: 'Biology',
    nameMk: 'Биологија',
    world: 'Џунгла свет',
    color: '#6BCB77',
    bgColor: '#E8F8EA',
    emoji: '🌿',
    unitsCount: 4,
    grades: [7, 8, 9],
  },
  {
    id: 'chemistry',
    name: 'Chemistry',
    nameMk: 'Хемија',
    world: 'Вулкан лаб',
    color: '#FF6B6B',
    bgColor: '#FFE8E8',
    emoji: '⚗️',
    unitsCount: 4,
    grades: [7, 8, 9],
  },
]

export const SUBJECTS: Subject[] = ALL_SUBJECTS

export function getSubjectsForGrade(grade: number): Subject[] {
  return ALL_SUBJECTS.filter((s) => s.grades.includes(grade))
}

export const getSubject = (id: string) =>
  ALL_SUBJECTS.find((s) => s.id === id)
